language: python
python:
  - '3.4'
addons:
  ssh_known_hosts: ssh.phx.nearlyfreespeech.net
sudo: enabled
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc  # Install old release first, so that we at least get the dependencies.
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
  - sudo apt-get install -y xsltproc
  - sudo apt-get install -y python3-pip
install:
  - pip3 install -r requirements.txt
script: make
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9e1d106ad00f_key -iv $encrypted_9e1d106ad00f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: make upload
  on:
    branch: master
