language: python
  - "3.5"
sudo: enabled
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y xsltproc
install:
  - pip install -r requirements.txt
script: make
